# Generated by Django 5.2.18 on 2026-10-07 10:25

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('crs', models.CharField(blank=True, max_length=64, null=True)),
                ('feature_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('geometry_type', models.CharField(blank=True, max_length=32, null=True)),
                ('geometry', models.JSONField(blank=True, null=True)),
                ('crs', models.CharField(blank=True, max_length=64, null=True)),
                ('properties', models.JSONField(default=dict)),
                ('measurement_type', models.CharField(blank=True, max_length=16, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=16, null=True)),
                ('measured_in_crs', models.CharField(blank=True, max_length=64, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='measurements.uploadedfile')),
            ],
            options={
                'ordering': ['index'],
                'constraints': [models.UniqueConstraint(fields=('file', 'index'), name='unique_feature_index_per_file')],
            },
        ),
    ]
