# Generated by Django 5.2.18 on 2026-10-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='method',
            field=models.CharField(choices=[('projected', 'Projected'), ('geodesic', 'Geodesic')], default='projected', max_length=16),
        ),
    ]
