# Generated by Django 5.2.18 on 2026-10-07 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_uploadedfile_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='maxx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='maxy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='minx',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='miny',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=models.Index(fields=['file', 'minx', 'maxx', 'miny', 'maxy'], name='feature_bbox_idx'),
        ),
    ]
